@startuml


participant MessageChannelResource
participant Client
participant MessageConsumerResource

MessageChannelResource -> Client : broadcast(Message message)
Client -> MessageConsumerResource : reject(String messageId, String message)


@enduml